server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/[접속할 DB명]?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&socketTimeout=10000&connectTimeout=10000
    username: [DB 아이디]
    password: [DB 비밀번호]
#    hikari:
#      connection-timeout: 250
#      max-lifetime: 500

# Devtool
#devtools:
#  livereload:
#    enabled: false

# Swagger
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Logging
logging.level:
   root: warn
   org.springframework:
     web: warn
     security: warn
     boot: warn
   org.hibernate:
     SQL: warn
   org.swmaestro.demo: warn
