server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
spring:
  # Mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/SwMaestro?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&socketTimeout=10000&connectTimeout=10000
    username: root
    password: mariaDB12(*
#    hikari:
#      connection-timeout: 250
#      max-lifetime: 500

# Devtool
#devtools:
#  livereload:
#    enabled: true

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Logging
logging.level:
  root: info
  org.springframework:
    web: info
    security: info
    boot: info
  org.hibernate:
    SQL: debug
  org.swmaestro.demo: debug
